### PR TITLE
Enhance README with full component description, system diagram and deployment instructions.

### PR DESCRIPTION
**Pull request by paulhowardarm**
Enhance README with full component description, system diagram and deployment instructions.

Signed-off-by: Paul Howard <paul.howard@arm.com>

### CODE REVIEW

**Comment by grealish** [comment]
So far looks good, I've a few things i'd like to add on diagram (or a detailed one) but possibly have to push to a separate branch

**Comment by paulhowardarm** [comment]
Is anything still pending for this review? Okay to merge? @grealish

**Comment by grealish** [comment]
Hi @paulhowardarm taking a look at this now, should have feedback and merge it over the weekend

**Comment by grealish** [comment]
Lets merge this anyways because there is allot of work behind this, especially in the documentation part, Thank @paulhowardarm ! very much appreciated.

We have some updates @firsou  worked on in a project that we can add/merge in a new PR/MR 

FYI: @ejmiller2 here's other branch with 2.8 fixes, unsure if it's still WIP
https://github.com/56kcloud/aws-greengrass-parsec-provider/compare/main...paulhowardarm:aws-greengrass-parsec-provider:phTestGG28x#diff-24a3960a11a42dcdf1e7222c6e296003328256abfba6aab8f76bb80797fa409eR27

**Review by grealish — COMMENTED** [review]
All good,

**Pull request merged**
